fix all 9

diff --git a/.github/workflows/automation.yml b/.github/workflows/automation.yml
--- a/.github/workflows/automation.yml
+++ b/.github/workflows/automation.yml
@@ -1,7 +1,8 @@
-name: Automation Test CRM
+name: Automation Test
 
 on:
-  workflow_dispatch:
+  push:
+    branches: [ "main" ]
   pull_request:
 
 jobs:
@@ -9,23 +10,42 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      # 1. Checkout repo
       - name: Checkout code
         uses: actions/checkout@v4
 
+      # 2. Setup Java
       - name: Setup Java
         uses: actions/setup-java@v4
         with:
-          distribution: temurin
-          java-version: 17
+          distribution: 'temurin'
+          java-version: '17'
 
-      - name: Run API Test
-        run: ./gradlew apiTest
+      # 3. permission gradlew
+      - name: Grant execute permission
+        run: chmod +x gradlew
 
-      - name: Run Web Test
+      # 4A. Run API Test
+      - name: Run API Tests
+        run: ./gradlew clean apiTest
+
+      # 4B. Run WEB / E2E Test
+      - name: Run Web Tests
         run: ./gradlew webTest
 
-      - name: Upload Cucumber Report
+      # 5. DEBUG
+      - name: Debug build folder
+        if: always()
+        run: |
+          echo "=== CHECK BUILD FOLDER ==="
+          ls -R build || echo "BUILD FOLDER NOT FOUND"
+
+      # 6. Upload All Report
+      - name: Upload Test Reports
+        if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: cucumber-report
-          path: reports/
+          name: test-reports
+          path: |
+            build/**/*.html
+            target/**/*.html
